name: github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.10'
          # mdbook-version: 'latest'

      - name: Build mdBook
        run: mdbook build
      
      - name: "Create CNAME file (Create DEPLOY_DOMAIN secret)"
        if: ${{ secrets.DEPLOY_DOMAIN }}
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "book/CNAME"
          FILE_DATA: '${{ secrets.DEPLOY_DOMAIN }}'

      - name: Push to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
